var Tasks, exports, tasksSchema;

tasksSchema = mongoose.Schema({
  name: String,
  completed: {
    type: Boolean,
    "default": false
  },
  category: String,
  created_at: {
    type: Date,
    "default": Date.now
  },
  updated_at: {
    type: Date,
    "default": Date.now
  }
});

tasksSchema["static"]("getAll", function(cb) {
  return this.find({}, cb);
});

tasksSchema["static"]("getById", function(id, cb) {
  return this.findOne({
    _id: id
  }, cb);
});

tasksSchema["static"]("getAllFromCategory", function(category, cb) {
  return this.find({
    category: category
  }, cb);
});

tasksSchema["static"]("create", function(data, cb) {
  var newTask;
  newTask = new Tasks(data);
  return newTask.save(cb);
});

tasksSchema["static"]("updateById", function(id, data, cb) {
  data.updated_at = Date.now();
  return this.update({
    _id: id
  }, data, cb);
});

tasksSchema["static"]("deleteById", function(id, cb) {
  return this.remove({
    _id: id
  }, cb);
});

Tasks = mongoose.model('Tasks', tasksSchema);

module.exports = exports = Tasks;

// ---
// generated by coffee-script 1.9.2